source 'https://rubygems.org'
ruby "2.4.1"

gem 'rails', '>= 5'
gem 'therubyracer'
gem 'execjs'

group :development, :test do
  gem 'pry-rails'
  gem 'faker'
  gem 'jquery-rails'
end

gem 'sqlite3'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 5.0'
  gem 'coffee-rails'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby
  gem 'uglifier'
end

gem 'jquery-rails'


